version: '3.7'
services:
  spark-master:
    image: ansjin/spark-master:${SPARK_VERSION}
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./task_usage/:/task_usage
      - ./machine_events:/machine_events
  spark-worker-1:
    image: ansjin/spark-worker:${SPARK_VERSION}
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./task_usage/:/task_usage
      - ./machine_events:/machine_events
